2021-03-27 16:22:36,397 - 
Downloading Utility Log. 
Log started.

Move log to Impt Logs if required as only the 10 most recent logs are kept.

2021-03-27 16:22:37,732 - Command: dl -youtube https://www.youtube.com/channel/UCPxHg4192hLDpTI2w7F9rPg
2021-03-27 16:22:37,732 - youtube link
2021-03-27 16:22:38,379 - file_cache is only supported with oauth2client<4.0.0
2021-03-27 16:22:38,384 - name 'Downloader' is not defined
Traceback (most recent call last):
  File "c:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 68, in check_youtube_api
    Downloader.apis["youtube"]
NameError: name 'Downloader' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Utilities/Scripts/url-dl-v2/main.py", line 240, in <module>
    parse_input()
  File "c:/Utilities/Scripts/url-dl-v2/main.py", line 123, in parse_input
    Downloader = youtube_extractor(Downloader) #Downloader_2 because Downloader causes errors.
  File "c:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 173, in youtube_extractor
    youtube_api = check_youtube_api()
  File "c:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 70, in check_youtube_api
    ini_youtube_api()
  File "c:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 64, in ini_youtube_api
    Downloader.apis["youtube"] = youtube
NameError: name 'Downloader' is not defined
2021-03-27 16:22:38,386 - 
Log Ended.
Total time: 0 hrs 0 min 1.99 sec

